"""add_follow_up_requests_table

Revision ID: 77fdeed4e58f
Revises: 9aa768931637
Create Date: 2026-07-10 03:03:58.229273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fdeed4e58f'
down_revision: Union[str, Sequence[str], None] = '9aa768931637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_up_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['original_submission_id'], ['contact_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_up_requests')
    # ### end Alembic commands ###
