"""added name and email to FollowUpRequest model

Revision ID: d2d597e0c6c3
Revises: 77fdeed4e58f
Create Date: 2026-07-10 08:49:08.822027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d597e0c6c3'
down_revision: Union[str, Sequence[str], None] = '77fdeed4e58f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM follow_up_requests")

    op.add_column('follow_up_requests', sa.Column('name', sa.String(), nullable=False))
    op.add_column('follow_up_requests', sa.Column('email', sa.String(), nullable=False))
    op.create_index(op.f('ix_follow_up_requests_email'), 'follow_up_requests', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_up_requests_email'), table_name='follow_up_requests')
    op.drop_column('follow_up_requests', 'email')
    op.drop_column('follow_up_requests', 'name')
    # ### end Alembic commands ###
